// <auto-generated>
// Generated by CodeGen_CharacterStatsUIClasses.
// Changes to this file will be overwritten.
// </auto-generated>

using Cysharp.Text;
using Insthync.DevExtension;
using System.Text;
using UnityEngine;

namespace MultiplayerARPG
{
    [System.Serializable]
    public partial class CharacterStatsTextGenerateData
    {
        public CharacterStats data;
        public bool isRate;
        public bool isBonus;
        public string hpStatsFormat = "UI_FORMAT_HP";
        public string hpRecoveryStatsFormat = "UI_FORMAT_HP_RECOVERY";
        public string hpLeechRateStatsFormat = "UI_FORMAT_HP_LEECH_RATE";
        public string mpStatsFormat = "UI_FORMAT_MP";
        public string mpRecoveryStatsFormat = "UI_FORMAT_MP_RECOVERY";
        public string mpLeechRateStatsFormat = "UI_FORMAT_MP_LEECH_RATE";
        public string staminaStatsFormat = "UI_FORMAT_STAMINA";
        public string staminaRecoveryStatsFormat = "UI_FORMAT_STAMINA_RECOVERY";
        public string staminaLeechRateStatsFormat = "UI_FORMAT_STAMINA_LEECH_RATE";
        public string foodStatsFormat = "UI_FORMAT_FOOD";
        public string waterStatsFormat = "UI_FORMAT_WATER";
        public string accuracyStatsFormat = "UI_FORMAT_ACCURACY";
        public string evasionStatsFormat = "UI_FORMAT_EVASION";
        public string criRateStatsFormat = "UI_FORMAT_CRITICAL_RATE";
        public string criDmgRateStatsFormat = "UI_FORMAT_CRITICAL_DAMAGE_RATE";
        public string blockRateStatsFormat = "UI_FORMAT_BLOCK_RATE";
        public string blockDmgRateStatsFormat = "UI_FORMAT_BLOCK_DAMAGE_RATE";
        public string moveSpeedStatsFormat = "UI_FORMAT_MOVE_SPEED";
        public string sprintSpeedStatsFormat = "UI_FORMAT_SPRINT_SPEED";
        public string atkSpeedStatsFormat = "UI_FORMAT_ATTACK_SPEED";
        public string weightLimitStatsFormat = "UI_FORMAT_WEIGHT";
        public string slotLimitStatsFormat = "UI_FORMAT_SLOT";
        public string goldRateStatsFormat = "UI_FORMAT_GOLD_RATE";
        public string expRateStatsFormat = "UI_FORMAT_EXP_RATE";
        public string itemDropRateStatsFormat = "UI_FORMAT_ITEM_DROP_RATE";
        public string jumpHeightStatsFormat = "UI_FORMAT_JUMP_HEIGHT";
        public string headDamageAbsorbsStatsFormat = "UI_FORMAT_HEAD_DAMAGE_ABSORBS";
        public string bodyDamageAbsorbsStatsFormat = "UI_FORMAT_BODY_DAMAGE_ABSORBS";
        public string fallDamageAbsorbsStatsFormat = "UI_FORMAT_FALL_DAMAGE_ABSORBS";
        public string gravityRateStatsFormat = "UI_FORMAT_GRAVITY_RATE";
        public string protectedSlotLimitStatsFormat = "UI_FORMAT_PROTECTED_SLOT_LIMIT";
        public string ammoCapacityModifierStatsFormat = "UI_FORMAT_AMMO_CAPACITY_MODIFIER";
        public string ammoCapacityRateStatsFormat = "UI_FORMAT_AMMO_CAPACITY_RATE";
        public string recoilModifierStatsFormat = "UI_FORMAT_RECOIL_MODIFIER";
        public string recoilYawModifierStatsFormat = "UI_FORMAT_RECOIL_YAW_MODIFIER";
        public string recoilRollModifierStatsFormat = "UI_FORMAT_RECOIL_ROLL_MODIFIER";
        public string recoilRateStatsFormat = "UI_FORMAT_RECOIL_RATE";
        public string recoilYawRateStatsFormat = "UI_FORMAT_RECOIL_YAW_RATE";
        public string recoilRollRateStatsFormat = "UI_FORMAT_RECOIL_ROLL_RATE";
        public string rateOfFireModifierStatsFormat = "UI_FORMAT_RATE_OF_FIRE_MODIFIER";
        public string rateOfFireRateStatsFormat = "UI_FORMAT_RATE_OF_FIRE_RATE";
        public string reloadDurationModifierStatsFormat = "UI_FORMAT_RELOAD_DURATION_MODIFIER";
        public string reloadDurationRateStatsFormat = "UI_FORMAT_RELOAD_DURATION_RATE";
        public string fireSpreadRangeModifierStatsFormat = "UI_FORMAT_FIRE_SPREAD_RANGE_MODIFIER";
        public string fireSpreadRangeRateStatsFormat = "UI_FORMAT_FIRE_SPREAD_RANGE_RATE";
        public string fireSpreadModifierStatsFormat = "UI_FORMAT_FIRE_SPREAD_MODIFIER";
        public string fireSpreadRateStatsFormat = "UI_FORMAT_FIRE_SPREAD_RATE";
        public string decreaseFoodDecreationStatsFormat = "UI_FORMAT_DECREASE_FOOD_DECREATION";
        public string decreaseWaterDecreationStatsFormat = "UI_FORMAT_DECREASE_WATER_DECREATION";
        public string decreaseStaminaDecreationStatsFormat = "UI_FORMAT_DECREASE_STAMINA_DECREATION";
        public string buyItemPriceRateStatsFormat = "UI_FORMAT_BUY_ITEM_PRICE_RATE";
        public string sellItemPriceRateStatsFormat = "UI_FORMAT_SELL_ITEM_PRICE_RATE";
        public TextWrapper uiTextHp;
        public TextWrapper uiTextHpRecovery;
        public TextWrapper uiTextHpLeechRate;
        public TextWrapper uiTextMp;
        public TextWrapper uiTextMpRecovery;
        public TextWrapper uiTextMpLeechRate;
        public TextWrapper uiTextStamina;
        public TextWrapper uiTextStaminaRecovery;
        public TextWrapper uiTextStaminaLeechRate;
        public TextWrapper uiTextFood;
        public TextWrapper uiTextWater;
        public TextWrapper uiTextAccuracy;
        public TextWrapper uiTextEvasion;
        public TextWrapper uiTextCriRate;
        public TextWrapper uiTextCriDmgRate;
        public TextWrapper uiTextBlockRate;
        public TextWrapper uiTextBlockDmgRate;
        public TextWrapper uiTextMoveSpeed;
        public TextWrapper uiTextSprintSpeed;
        public TextWrapper uiTextAtkSpeed;
        public TextWrapper uiTextWeightLimit;
        public TextWrapper uiTextSlotLimit;
        public TextWrapper uiTextGoldRate;
        public TextWrapper uiTextExpRate;
        public TextWrapper uiTextItemDropRate;
        public TextWrapper uiTextJumpHeight;
        public TextWrapper uiTextHeadDamageAbsorbs;
        public TextWrapper uiTextBodyDamageAbsorbs;
        public TextWrapper uiTextFallDamageAbsorbs;
        public TextWrapper uiTextGravityRate;
        public TextWrapper uiTextProtectedSlotLimit;
        public TextWrapper uiTextAmmoCapacityModifier;
        public TextWrapper uiTextAmmoCapacityRate;
        public TextWrapper uiTextRecoilModifier;
        public TextWrapper uiTextRecoilYawModifier;
        public TextWrapper uiTextRecoilRollModifier;
        public TextWrapper uiTextRecoilRate;
        public TextWrapper uiTextRecoilYawRate;
        public TextWrapper uiTextRecoilRollRate;
        public TextWrapper uiTextRateOfFireModifier;
        public TextWrapper uiTextRateOfFireRate;
        public TextWrapper uiTextReloadDurationModifier;
        public TextWrapper uiTextReloadDurationRate;
        public TextWrapper uiTextFireSpreadRangeModifier;
        public TextWrapper uiTextFireSpreadRangeRate;
        public TextWrapper uiTextFireSpreadModifier;
        public TextWrapper uiTextFireSpreadRate;
        public TextWrapper uiTextDecreaseFoodDecreation;
        public TextWrapper uiTextDecreaseWaterDecreation;
        public TextWrapper uiTextDecreaseStaminaDecreation;
        public TextWrapper uiTextBuyItemPriceRate;
        public TextWrapper uiTextSellItemPriceRate;

        public string numberFormatSimple = "N0";
        public string numberFormatRate = "N2";

        public string GetText(Color bonusIncreaseColor, Color bonusDecreaseColor)
        {
            StringBuilder statsStringBuilder = new StringBuilder();

            // Hp
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(hpStatsFormat), data.hp, uiTextHp, bonusIncreaseColor, bonusDecreaseColor);

            // Hp Recovery
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(hpRecoveryStatsFormat), data.hpRecovery, uiTextHpRecovery, bonusIncreaseColor, bonusDecreaseColor);

            // Hp Leech Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(hpLeechRateStatsFormat), data.hpLeechRate, uiTextHpLeechRate, bonusIncreaseColor, bonusDecreaseColor);

            // Mp
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(mpStatsFormat), data.mp, uiTextMp, bonusIncreaseColor, bonusDecreaseColor);

            // Mp Recovery
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(mpRecoveryStatsFormat), data.mpRecovery, uiTextMpRecovery, bonusIncreaseColor, bonusDecreaseColor);

            // Mp Leech Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(mpLeechRateStatsFormat), data.mpLeechRate, uiTextMpLeechRate, bonusIncreaseColor, bonusDecreaseColor);

            // Stamina
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(staminaStatsFormat), data.stamina, uiTextStamina, bonusIncreaseColor, bonusDecreaseColor);

            // Stamina Recovery
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(staminaRecoveryStatsFormat), data.staminaRecovery, uiTextStaminaRecovery, bonusIncreaseColor, bonusDecreaseColor);

            // Stamina Leech Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(staminaLeechRateStatsFormat), data.staminaLeechRate, uiTextStaminaLeechRate, bonusIncreaseColor, bonusDecreaseColor);

            // Food
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(foodStatsFormat), data.food, uiTextFood, bonusIncreaseColor, bonusDecreaseColor);

            // Water
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(waterStatsFormat), data.water, uiTextWater, bonusIncreaseColor, bonusDecreaseColor);

            // Accuracy
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(accuracyStatsFormat), data.accuracy, uiTextAccuracy, bonusIncreaseColor, bonusDecreaseColor);

            // Evasion
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(evasionStatsFormat), data.evasion, uiTextEvasion, bonusIncreaseColor, bonusDecreaseColor);

            // Cri Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(criRateStatsFormat), data.criRate, uiTextCriRate, bonusIncreaseColor, bonusDecreaseColor);

            // Cri Dmg Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(criDmgRateStatsFormat), data.criDmgRate, uiTextCriDmgRate, bonusIncreaseColor, bonusDecreaseColor);

            // Block Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(blockRateStatsFormat), data.blockRate, uiTextBlockRate, bonusIncreaseColor, bonusDecreaseColor);

            // Block Dmg Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(blockDmgRateStatsFormat), data.blockDmgRate, uiTextBlockDmgRate, bonusIncreaseColor, bonusDecreaseColor);

            // Move Speed
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(moveSpeedStatsFormat), data.moveSpeed, uiTextMoveSpeed, bonusIncreaseColor, bonusDecreaseColor);

            // Sprint Speed
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(sprintSpeedStatsFormat), data.sprintSpeed, uiTextSprintSpeed, bonusIncreaseColor, bonusDecreaseColor);

            // Atk Speed
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(atkSpeedStatsFormat), data.atkSpeed, uiTextAtkSpeed, bonusIncreaseColor, bonusDecreaseColor);

            // Weight Limit
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(weightLimitStatsFormat), data.weightLimit, uiTextWeightLimit, bonusIncreaseColor, bonusDecreaseColor);

            // Slot Limit
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(slotLimitStatsFormat), data.slotLimit, uiTextSlotLimit, bonusIncreaseColor, bonusDecreaseColor);

            // Gold Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(goldRateStatsFormat), data.goldRate, uiTextGoldRate, bonusIncreaseColor, bonusDecreaseColor);

            // Exp Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(expRateStatsFormat), data.expRate, uiTextExpRate, bonusIncreaseColor, bonusDecreaseColor);

            // Item Drop Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(itemDropRateStatsFormat), data.itemDropRate, uiTextItemDropRate, bonusIncreaseColor, bonusDecreaseColor);

            // Jump Height
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(jumpHeightStatsFormat), data.jumpHeight, uiTextJumpHeight, bonusIncreaseColor, bonusDecreaseColor);

            // Head Damage Absorbs
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(headDamageAbsorbsStatsFormat), data.headDamageAbsorbs, uiTextHeadDamageAbsorbs, bonusIncreaseColor, bonusDecreaseColor);

            // Body Damage Absorbs
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(bodyDamageAbsorbsStatsFormat), data.bodyDamageAbsorbs, uiTextBodyDamageAbsorbs, bonusIncreaseColor, bonusDecreaseColor);

            // Fall Damage Absorbs
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(fallDamageAbsorbsStatsFormat), data.fallDamageAbsorbs, uiTextFallDamageAbsorbs, bonusIncreaseColor, bonusDecreaseColor);

            // Gravity Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(gravityRateStatsFormat), data.gravityRate, uiTextGravityRate, bonusIncreaseColor, bonusDecreaseColor);

            // Protected Slot Limit
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(protectedSlotLimitStatsFormat), data.protectedSlotLimit, uiTextProtectedSlotLimit, bonusIncreaseColor, bonusDecreaseColor);

            // Ammo Capacity Modifier
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(ammoCapacityModifierStatsFormat), data.ammoCapacityModifier, uiTextAmmoCapacityModifier, bonusIncreaseColor, bonusDecreaseColor);

            // Ammo Capacity Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(ammoCapacityRateStatsFormat), data.ammoCapacityRate, uiTextAmmoCapacityRate, bonusIncreaseColor, bonusDecreaseColor);

            // Recoil Modifier
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(recoilModifierStatsFormat), data.recoilModifier, uiTextRecoilModifier, bonusIncreaseColor, bonusDecreaseColor);

            // Recoil Yaw Modifier
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(recoilYawModifierStatsFormat), data.recoilYawModifier, uiTextRecoilYawModifier, bonusIncreaseColor, bonusDecreaseColor);

            // Recoil Roll Modifier
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(recoilRollModifierStatsFormat), data.recoilRollModifier, uiTextRecoilRollModifier, bonusIncreaseColor, bonusDecreaseColor);

            // Recoil Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(recoilRateStatsFormat), data.recoilRate, uiTextRecoilRate, bonusIncreaseColor, bonusDecreaseColor);

            // Recoil Yaw Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(recoilYawRateStatsFormat), data.recoilYawRate, uiTextRecoilYawRate, bonusIncreaseColor, bonusDecreaseColor);

            // Recoil Roll Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(recoilRollRateStatsFormat), data.recoilRollRate, uiTextRecoilRollRate, bonusIncreaseColor, bonusDecreaseColor);

            // Rate Of Fire Modifier
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(rateOfFireModifierStatsFormat), data.rateOfFireModifier, uiTextRateOfFireModifier, bonusIncreaseColor, bonusDecreaseColor);

            // Rate Of Fire Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(rateOfFireRateStatsFormat), data.rateOfFireRate, uiTextRateOfFireRate, bonusIncreaseColor, bonusDecreaseColor);

            // Reload Duration Modifier
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(reloadDurationModifierStatsFormat), data.reloadDurationModifier, uiTextReloadDurationModifier, bonusIncreaseColor, bonusDecreaseColor);

            // Reload Duration Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(reloadDurationRateStatsFormat), data.reloadDurationRate, uiTextReloadDurationRate, bonusIncreaseColor, bonusDecreaseColor);

            // Fire Spread Range Modifier
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(fireSpreadRangeModifierStatsFormat), data.fireSpreadRangeModifier, uiTextFireSpreadRangeModifier, bonusIncreaseColor, bonusDecreaseColor);

            // Fire Spread Range Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(fireSpreadRangeRateStatsFormat), data.fireSpreadRangeRate, uiTextFireSpreadRangeRate, bonusIncreaseColor, bonusDecreaseColor);

            // Fire Spread Modifier
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(fireSpreadModifierStatsFormat), data.fireSpreadModifier, uiTextFireSpreadModifier, bonusIncreaseColor, bonusDecreaseColor);

            // Fire Spread Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(fireSpreadRateStatsFormat), data.fireSpreadRate, uiTextFireSpreadRate, bonusIncreaseColor, bonusDecreaseColor);

            // Decrease Food Decreation
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(decreaseFoodDecreationStatsFormat), data.decreaseFoodDecreation, uiTextDecreaseFoodDecreation, bonusIncreaseColor, bonusDecreaseColor);

            // Decrease Water Decreation
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(decreaseWaterDecreationStatsFormat), data.decreaseWaterDecreation, uiTextDecreaseWaterDecreation, bonusIncreaseColor, bonusDecreaseColor);

            // Decrease Stamina Decreation
            GetSingleStatsText(statsStringBuilder, isRate || false, LanguageManager.GetText(decreaseStaminaDecreationStatsFormat), data.decreaseStaminaDecreation, uiTextDecreaseStaminaDecreation, bonusIncreaseColor, bonusDecreaseColor);

            // Buy Item Price Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(buyItemPriceRateStatsFormat), data.buyItemPriceRate, uiTextBuyItemPriceRate, bonusIncreaseColor, bonusDecreaseColor);

            // Sell Item Price Rate
            GetSingleStatsText(statsStringBuilder, isRate || true, LanguageManager.GetText(sellItemPriceRateStatsFormat), data.sellItemPriceRate, uiTextSellItemPriceRate, bonusIncreaseColor, bonusDecreaseColor);

            // Dev Extension
            // How to implement it?:
            // /*
            //  * - Add `customStat1` to `CharacterStats` partial class file
            //  * - Add `customStat1StatsFormat` to `CharacterStatsTextGenerateData`
            //  * - Add `uiTextCustomStat1` to `CharacterStatsTextGenerateData`
            //  */
            // [DevExtMethods("GetText")]
            // public void GetText_Ext(StringBuilder statsString)
            // {
            //   string tempValue;
            //   string statsStringPart;
            //   tempValue = isRate ? (data.customStat1 * 100).ToString("N2") : data.customStat1.ToString("N0");
            //   statsStringPart = ZString.Format(LanguageManager.GetText(customStat1StatsFormat), tempValue);
            //   if (data.customStat1 != 0)
            //   {
            //       if (statsString.Length > 0)
            //           statsString.Append('\n');
            //       statsString.Append(statsStringPart);
            //   }
            //   if (uiTextCustomStat1 != null)
            //       uiTextCustomStat1.text = statsStringPart;
            // }
            this.InvokeInstanceDevExtMethods("GetText", statsStringBuilder, bonusIncreaseColor, bonusDecreaseColor);

            return statsStringBuilder.ToString();
        }

        public void GetSingleStatsText(StringBuilder builder, bool isRateStats, string format, float value, TextWrapper textComponent, Color bonusIncreaseColor, Color bonusDecreaseColor)
        {
            // Determine the correct format string based on whether the stat is a rate
            string numberFormat = isRateStats ? numberFormatRate : numberFormatSimple;

            // Calculate the value to display, adjusting for rates if necessary
            string tempValue = isRateStats ? (value * 100).ToString(numberFormat) : value.ToString(numberFormat);

            // Construct the display string
            string statsStringPart = ZString.Concat(isBonus && value >= 0 ? "+" : string.Empty, ZString.Format(
                format,
                tempValue));

            // Append the stat text to the builder if the value is not zero
            if (value != 0)
            {
                if (builder.Length > 0)
                    builder.Append('\n');
                builder.Append(statsStringPart);
            }

            // Set the text component if it's provided
            if (textComponent != null)
            {
                if (value != 0f)
                {
                    if (isBonus)
                    {
                        if (value >= 0)
                            textComponent.color = bonusIncreaseColor;
                        else
                            textComponent.color = bonusDecreaseColor;
                    }
                    textComponent.text = statsStringPart;
                    textComponent.SetGameObjectActive(true);
                }
                else
                {
                    textComponent.SetGameObjectActive(false);
                }
            }
        }

        public void GetBooleanStatsText(StringBuilder builder, string text, bool value, TextWrapper textComponent)
        {
            if (isRate)
                return;
            string statsStringPart = value ? text : string.Empty;
            if (value)
            {
                if (builder.Length > 0)
                    builder.Append('\n');
                builder.Append(statsStringPart);
            }
            if (textComponent != null)
                textComponent.text = statsStringPart;
        }
    }
}
